/* =====================================================================
   LIMPEZA OPCIONAL (APENAS SE PRECISAR RECRIAR DO ZERO)
   ===================================================================== */
DROP TABLE TRILHA_SKILL_NECESSARIA CASCADE CONSTRAINTS;
DROP TABLE USUARIO_SKILL           CASCADE CONSTRAINTS;
DROP TABLE USUARIO_TRILHA          CASCADE CONSTRAINTS;
DROP TABLE USUARIO_AREA            CASCADE CONSTRAINTS;
DROP TABLE CURSO_RECOMENDADO       CASCADE CONSTRAINTS;
DROP TABLE SKILL                   CASCADE CONSTRAINTS;
DROP TABLE AREA                    CASCADE CONSTRAINTS;
DROP TABLE TRILHA                  CASCADE CONSTRAINTS;
DROP TABLE USUARIO                 CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_AREA;
DROP SEQUENCE SEQ_SKILL;
DROP SEQUENCE SEQ_TRILHA;
DROP SEQUENCE SEQ_CURSO;

/* =====================================================================
   CRIAÇÃO DAS TABELAS (MODELO FÍSICO)
   ===================================================================== */

CREATE TABLE USUARIO (
    idUsuario        NUMBER(10)      NOT NULL,
    nome             VARCHAR2(100)   NOT NULL,
    sobrenome        VARCHAR2(100)   NOT NULL,
    email            VARCHAR2(150)   NOT NULL,
    telefone         VARCHAR2(20)    NOT NULL,
    dtCadastro       DATE            NOT NULL,
    estado           CHAR(2)         NOT NULL,
    objetivoCarreira VARCHAR2(500)   NOT NULL,
    statusPerfil     VARCHAR2(20)    NOT NULL,
    CONSTRAINT USUARIO_PK          PRIMARY KEY (idUsuario),
    CONSTRAINT USUARIO_UK_EMAIL    UNIQUE (email),
    CONSTRAINT USUARIO_CHK_STATUS  CHECK (statusPerfil IN ('ATIVO','INATIVO','PENDENTE'))
);

CREATE TABLE AREA (
    idArea    NUMBER(10)     NOT NULL,
    nome      VARCHAR2(100)  NOT NULL,
    descricao VARCHAR2(300)  NOT NULL,
    dtCriacao DATE           NOT NULL,
    CONSTRAINT AREA_PK         PRIMARY KEY (idArea),
    CONSTRAINT AREA_UK_NOME    UNIQUE (nome)
);

CREATE TABLE SKILL (
    idSkill      NUMBER(10)    NOT NULL,
    nome         VARCHAR2(100) NOT NULL,
    descricao    VARCHAR2(500) NOT NULL,
    nivel        VARCHAR2(20)  NOT NULL,
    categoria    VARCHAR2(50)  NOT NULL,
    ultimoAcesso DATE          NOT NULL,
    tipo         VARCHAR2(50)  NOT NULL,
    CONSTRAINT SKILL_PK          PRIMARY KEY (idSkill),
    CONSTRAINT SKILL_UK_NOME     UNIQUE (nome),
    CONSTRAINT SKILL_CHK_NIVEL   CHECK (nivel IN ('BASICO','INTERMEDIARIO','AVANCADO'))
);

CREATE TABLE TRILHA (
    idTrilha  NUMBER(10)    NOT NULL,
    nome      VARCHAR2(150) NOT NULL,
    descricao VARCHAR2(500) NOT NULL,
    nivel     VARCHAR2(20)  NOT NULL,
    objetivo  VARCHAR2(500) NOT NULL,
    status    VARCHAR2(20)  NOT NULL,
    dtCriacao DATE          NOT NULL,
    CONSTRAINT TRILHA_PK           PRIMARY KEY (idTrilha),
    CONSTRAINT TRILHA_UK_NOME      UNIQUE (nome),
    CONSTRAINT TRILHA_CHK_STATUS   CHECK (status IN ('ATIVA','INATIVA'))
);

CREATE TABLE CURSO_RECOMENDADO (
    idCurso         NUMBER        NOT NULL,
    nome            VARCHAR2(200) NOT NULL,
    url             VARCHAR2(400) NOT NULL,
    TRILHA_idTrilha NUMBER(10)    NOT NULL,
    plataforma      VARCHAR2(100) NOT NULL,
    duracaoHoras    NUMBER(5)     NOT NULL,
    CONSTRAINT CURSO_RECOMENDADO_PK        PRIMARY KEY (idCurso),
    CONSTRAINT CURSO_RECOMENDADO_CHK_DUR   CHECK (duracaoHoras > 0)
);

CREATE TABLE USUARIO_AREA (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    AREA_idArea       NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_AREA_PK PRIMARY KEY (USUARIO_idUsuario, AREA_idArea)
);

CREATE TABLE USUARIO_TRILHA (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    TRILHA_idTrilha   NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_TRILHA_PK PRIMARY KEY (USUARIO_idUsuario, TRILHA_idTrilha)
);

CREATE TABLE USUARIO_SKILL (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    SKILL_idSkill     NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_SKILL_PK PRIMARY KEY (USUARIO_idUsuario, SKILL_idSkill)
);

CREATE TABLE TRILHA_SKILL_NECESSARIA (
    TRILHA_idTrilha NUMBER(10) NOT NULL,
    SKILL_idSkill   NUMBER(10) NOT NULL,
    CONSTRAINT TRILHA_SKILL_NECESSARIA_PK PRIMARY KEY (TRILHA_idTrilha, SKILL_idSkill)
);

/* =====================================================================
   FOREIGN KEYS
   ===================================================================== */

ALTER TABLE USUARIO_AREA
  ADD CONSTRAINT USUARIO_AREA_USUARIO_FK
      FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_AREA
  ADD CONSTRAINT USUARIO_AREA_AREA_FK
      FOREIGN KEY (AREA_idArea) REFERENCES AREA (idArea);

ALTER TABLE USUARIO_TRILHA
  ADD CONSTRAINT USUARIO_TRILHA_USUARIO_FK
      FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_TRILHA
  ADD CONSTRAINT USUARIO_TRILHA_TRILHA_FK
      FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

ALTER TABLE USUARIO_SKILL
  ADD CONSTRAINT USUARIO_SKILL_USUARIO_FK
      FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_SKILL
  ADD CONSTRAINT USUARIO_SKILL_SKILL_FK
      FOREIGN KEY (SKILL_idSkill) REFERENCES SKILL (idSkill);

ALTER TABLE TRILHA_SKILL_NECESSARIA
  ADD CONSTRAINT TRILHA_SKILL_NEC_TRILHA_FK
      FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

ALTER TABLE TRILHA_SKILL_NECESSARIA
  ADD CONSTRAINT TRILHA_SKILL_NEC_SKILL_FK
      FOREIGN KEY (SKILL_idSkill) REFERENCES SKILL (idSkill);

ALTER TABLE CURSO_RECOMENDADO
  ADD CONSTRAINT CURSO_RECOMENDADO_TRILHA_FK
      FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

/* =====================================================================
   SEQUENCES (SUPORTE A INSERT VIA BACKEND E PROCEDURES)
   ===================================================================== */

CREATE SEQUENCE SEQ_USUARIO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AREA    START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SKILL   START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRILHA  START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CURSO   START WITH 100 INCREMENT BY 1 NOCACHE;
