/* =====================================================================
   01 — DDL ESTRUTURAL DO PROJETO EQUALPATH (ATUALIZADO)
   ===================================================================== */

------------------------------
-- TABELA: USUARIO
------------------------------
CREATE TABLE USUARIO (
    idUsuario        NUMBER(10)      NOT NULL,
    nome             VARCHAR2(100)   NOT NULL,
    sobrenome        VARCHAR2(100)   NOT NULL,
    email            VARCHAR2(150)   NOT NULL,
    telefone         VARCHAR2(20)    NOT NULL,
    dtCadastro       DATE            NOT NULL,
    estado           VARCHAR2(2 CHAR) NOT NULL,   
    objetivoCarreira VARCHAR2(500)   NOT NULL,
    statusPerfil     VARCHAR2(20)    NOT NULL,
    CONSTRAINT USUARIO_PK       PRIMARY KEY (idUsuario),
    CONSTRAINT USUARIO_UK_EMAIL UNIQUE (email)
);

------------------------------
-- TABELA: AREA
------------------------------
CREATE TABLE AREA (
    idArea    NUMBER(10)     NOT NULL,
    nome      VARCHAR2(100)  NOT NULL,
    descricao VARCHAR2(300)  NOT NULL,
    dtCriacao DATE           NOT NULL,
    CONSTRAINT AREA_PK      PRIMARY KEY (idArea),
    CONSTRAINT AREA_UK_NOME UNIQUE (nome)
);

------------------------------
-- TABELA: SKILL
------------------------------
CREATE TABLE SKILL (
    idSkill      NUMBER(10)    NOT NULL,
    nome         VARCHAR2(100) NOT NULL,
    descricao    VARCHAR2(500) NOT NULL,
    nivel        VARCHAR2(20)  NOT NULL,
    categoria    VARCHAR2(50)  NOT NULL,
    ultimoAcesso DATE          NOT NULL,
    tipo         VARCHAR2(50)  NOT NULL,
    CONSTRAINT SKILL_PK       PRIMARY KEY (idSkill),
    CONSTRAINT SKILL_UK_NOME  UNIQUE (nome)
);

------------------------------
-- TABELA: TRILHA
------------------------------
CREATE TABLE TRILHA (
    idTrilha  NUMBER(10)    NOT NULL,
    nome      VARCHAR2(150) NOT NULL,
    descricao VARCHAR2(500) NOT NULL,
    nivel     VARCHAR2(20)  NOT NULL,
    objetivo  VARCHAR2(500) NOT NULL,
    status    VARCHAR2(20)  NOT NULL,
    dtCriacao DATE          NOT NULL,
    CONSTRAINT TRILHA_PK      PRIMARY KEY (idTrilha),
    CONSTRAINT TRILHA_UK_NOME UNIQUE (nome)
);

------------------------------
-- TABELA: CURSO_RECOMENDADO
------------------------------
CREATE TABLE CURSO_RECOMENDADO (
    idCurso         NUMBER        NOT NULL,
    nome            VARCHAR2(200) NOT NULL,
    url             VARCHAR2(400) NOT NULL,
    TRILHA_idTrilha NUMBER(10)    NOT NULL,
    plataforma      VARCHAR2(100) NOT NULL,
    duracaoHoras    NUMBER(5)     NOT NULL,
    CONSTRAINT CURSO_RECOMENDADO_PK PRIMARY KEY (idCurso)
);

------------------------------
-- TABELAS DE RELACIONAMENTO
------------------------------
CREATE TABLE USUARIO_AREA (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    AREA_idArea       NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_AREA_PK PRIMARY KEY (USUARIO_idUsuario, AREA_idArea)
);

CREATE TABLE USUARIO_TRILHA (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    TRILHA_idTrilha   NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_TRILHA_PK PRIMARY KEY (USUARIO_idUsuario, TRILHA_idTrilha)
);

CREATE TABLE USUARIO_SKILL (
    USUARIO_idUsuario NUMBER(10) NOT NULL,
    SKILL_idSkill     NUMBER(10) NOT NULL,
    CONSTRAINT USUARIO_SKILL_PK PRIMARY KEY (USUARIO_idUsuario, SKILL_idSkill)
);

CREATE TABLE TRILHA_SKILL_NECESSARIA (
    TRILHA_idTrilha NUMBER(10) NOT NULL,
    SKILL_idSkill   NUMBER(10) NOT NULL,
    CONSTRAINT TRILHA_SKILL_NECESSARIA_PK PRIMARY KEY (TRILHA_idTrilha, SKILL_idSkill)
);

------------------------------
-- FOREIGN KEYS
------------------------------
ALTER TABLE USUARIO_AREA
  ADD CONSTRAINT USUARIO_AREA_USUARIO_FK FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_AREA
  ADD CONSTRAINT USUARIO_AREA_AREA_FK FOREIGN KEY (AREA_idArea) REFERENCES AREA (idArea);

ALTER TABLE USUARIO_TRILHA
  ADD CONSTRAINT USUARIO_TRILHA_USUARIO_FK FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_TRILHA
  ADD CONSTRAINT USUARIO_TRILHA_TRILHA_FK FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

ALTER TABLE USUARIO_SKILL
  ADD CONSTRAINT USUARIO_SKILL_USUARIO_FK FOREIGN KEY (USUARIO_idUsuario) REFERENCES USUARIO (idUsuario);

ALTER TABLE USUARIO_SKILL
  ADD CONSTRAINT USUARIO_SKILL_SKILL_FK FOREIGN KEY (SKILL_idSkill) REFERENCES SKILL (idSkill);

ALTER TABLE TRILHA_SKILL_NECESSARIA
  ADD CONSTRAINT TRILHA_SKILL_NEC_TRILHA_FK FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

ALTER TABLE TRILHA_SKILL_NECESSARIA
  ADD CONSTRAINT TRILHA_SKILL_NEC_SKILL_FK FOREIGN KEY (SKILL_idSkill) REFERENCES SKILL (idSkill);

ALTER TABLE CURSO_RECOMENDADO
  ADD CONSTRAINT CURSO_RECOMENDADO_TRILHA_FK FOREIGN KEY (TRILHA_idTrilha) REFERENCES TRILHA (idTrilha);

------------------------------
-- SEQUENCES
------------------------------
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AREA    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SKILL   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRILHA  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CURSO   START WITH 1 INCREMENT BY 1 NOCACHE;
